### PR TITLE
Dependency & license updates + 0.13.10 release

### PR DESCRIPTION
**Pull request by towerofnix**
License updates includes bringing the copyright dates up to 2023 (am I allowed to do that for you two? LOL) and using my main semi-professional name and current email, package.json is updated to 0.13.10.

A quick pass across the open PRs shows this covers everything Dependabot brought up, and npm audit reports zero vulnerabilities. Tests still passing locally.

Made sure to pass all this through Node 12 since that's the version `.github/workflows/nodejs.yml` is configured for!

```zsh
# jest 28 is last version compatible with node 12
# but ts-jest 27 is last version compatible with typescript 3
npm install jest@27.5.1
npm install ts-jest@27.5.1
npm install @types/jest@27.5.2

# miscellaneous outdated packages
npm install @types/jszip@3.4.1
npm install @types/prettier@1.19.1
npm install @typescript-eslint/eslint-plugin@2.34.0
npm install @typescript-eslint/parser@2.34.0
npm install eslint-config-prettier@6.15.0
npm install eslint-plugin-prettier@3.4.1
npm install jszip@3.10.1
npm install typescript@3.9.10
```

### CODE REVIEW

**Comment by towerofnix** [comment]
Noo, errors, etc, woe is me

**Review by PullJosh — APPROVED** [review]
Looks good to me! Not sure how updating the copyright dates works legally, but I'm on board 👍

**Comment by towerofnix** [comment]
It's apparently just fine to drop the year entirely, which I wouldn't mind: [lots of links and examples from this blog post.](https://hynek.me/til/copyright-years/) /cc @PullJosh @adroitwhiz Does that sound good to you two?

**Comment by PullJosh** [comment]
Love it!

**Comment by towerofnix** [comment]
Cool! That isn't in any way a substantial package change so, this is good for merge as-is — if adroitwhiz corroborates we can drop the year from copyright text later.

I wrangled npm a bit to a state where everything is more or less OK again. There are a lot of audit errors but they're all from outdated jest, so unless we start processing arbitrary user input as a function of our CI testing environment, I think we're OK.

**Comment by adroitwhiz** [comment]
I'm fine with dropping the year from the notice

**Pull request merged**
